services:
  - type: web
    name: aerva-mqtt-broker
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node mqtt-broker.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: WS_PORT
        value: 10000
    headers:
      - path: "/*"
        headers:
          - key: "Access-Control-Allow-Origin"
            value: "*"
          - key: "Access-Control-Allow-Methods"
            value: "GET, POST, PUT, DELETE, OPTIONS"
    branches:
      - main
    autodeploy: true
